# Generated by Django 5.1.4 on 2025-01-02 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InventoryServices', '0002_initial'),
        ('OrderServices', '0001_initial'),
        ('ProductServices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_user_id_purchaseorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cancelled_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by_user_id_purchaseorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_id_purchaseorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='domain_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_purchaseorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='last_updated_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_updateb_by_user_id_purchaseorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_by_user_id_purchaseorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='returned_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_by_user_id_purchaseorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user_id_purchaseorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_id_purchaseorder', to='InventoryServices.warehouse'),
        ),
        migrations.AddField(
            model_name='purchaseorderinwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_purchaseorderinwardedlog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderinwardedlog',
            name='inwarded_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inwarded_by_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderinwardedlog',
            name='po_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_order_id', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderiteminwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_purchaseorderiteminwardedlog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='approved_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_user_id_purchaseorderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='cancelled_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by_user_id_purchaseorderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='created_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_id_purchaseorderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='domain_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_purchaseorderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='po_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_id_purchaseorderitems', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='ProductServices.products'),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='recieved_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_by_user_id_purchaseorderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='returned_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_by_user_id_purchaseorderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='updated_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user_id_purchaseorder_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderiteminwardedlog',
            name='po_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_item_id', to='OrderServices.purchaseorderitems'),
        ),
        migrations.AddField(
            model_name='purchaseorderlogs',
            name='created_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_id_purchaseorderlogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderlogs',
            name='domain_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_purchaseorderlogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderlogs',
            name='po_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_id_purchaseorderlogs', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='approved_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_user_id_salesorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='cancelled_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by_user_id_salesorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='created_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_id_salesorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='domain_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_salesorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='last_updateb_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_updateb_by_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='recieved_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_by_user_id_salesorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='returned_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_by_user_id_salesorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='updated_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user_id_salesorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitemoutwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_salesorderitemoutwardedlog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='approved_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_user_id_salesorderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='cancelled_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by_user_id_salesorderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='created_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_id_salesorderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='domain_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_salesorderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id_so', to='ProductServices.products'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='returned_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_by_user_id_salesorderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='shipped_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_by_user_id_salesorderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='so_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_id_salesorderitems', to='OrderServices.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='updated_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user_id_salesorderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitemoutwardedlog',
            name='so_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_item_id', to='OrderServices.salesorderitems'),
        ),
        migrations.AddField(
            model_name='salesorderlogs',
            name='created_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_id_salesorderlogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderlogs',
            name='domain_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_salesorderlogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderlogs',
            name='so_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_id_salesorderlogs', to='OrderServices.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderoutwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_salesorderoutwardedlog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderoutwardedlog',
            name='outwarded_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outwarded_by_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderoutwardedlog',
            name='so_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_order_id', to='OrderServices.salesorder'),
        ),
    ]
